### ISSUE TITLE
cspca-case-level-likelihood.json issue

### ISSUE THREAD

**Issue by jakubMitura14** [DIAGNijmegen/picai_nnunet_semi_supervised_gc_algorithm#1]
Hello I downloaded the code and when I tried to run the test.sh after succesfully building docker I get an error like below, how to reselve it?

Thanks!

```
bash /media/jakub/NewVolume/projects/prostateOpiProjects/picaiToSend/picai_OPI_Mitura/picai_nnunet_semi_supervised_gc_algorithm-master/test.sh
/media/jakub/NewVolume/projects/prostateOpiProjects/picaiToSend/picai_OPI_Mitura/picai_nnunet_semi_supervised_gc_algorithm-master/test.sh: line 5: ./build.sh: No such file or directory
1+0 records in
1+0 records out
32 bytes copied, 1,5233e-05 s, 2,1 MB/s
picai_baseline_nnunet_semi_supervised_processor-output-767d48117b
Unable to find image 'picai_baseline_nnunet_semi_supervised_processor:latest' locally
docker: Error response from daemon: pull access denied for picai_baseline_nnunet_semi_supervised_processor, repository does not exist or may require 'docker login': denied: requested access to the resource is denied.
See 'docker run --help'.
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/SimpleITK-0.9.1.post2-py2.7-linux-x86_64.egg/SimpleITK/SimpleITK.py", line 7724, in ReadImage
    return _SimpleITK.ReadImage(*args)
RuntimeError: Exception thrown in SimpleITK ReadImage: /usr/src/SimpleITK/Code/IO/src/sitkImageReaderBase.cxx:71:
sitk::ERROR: The file "/output/images/cspca-detection-map/cspca_detection_map.mha" does not exist.
Expected detection map was not found...
Traceback (most recent call last):
  File "<string>", line 1, in <module>
IOError: [Errno 2] No such file or directory: '/output/cspca-case-level-likelihood.json'
Expected case-level prediction was not found...
picai_baseline_nnunet_semi_supervised_processor-output-767d48117b
```

**Comment by joeranbosma** [comment]
Hi @jakubMitura14,

Are you sure building the Docker container was successful? The error indicates that it cannot find 'picai_baseline_nnunet_semi_supervised_processor:latest' locally, which should have been built & tagged when running build.sh. 

After that it tries to pull this image from Docker Hub, where it cannot find it (and it should not, because it should be your local image).

Could you try to first move to the Docker directory (`/media/jakub/NewVolume/projects/prostateOpiProjects/picaiToSend/picai_OPI_Mitura/picai_nnunet_semi_supervised_gc_algorithm-master/`), and then run `bash build.sh` first, and check there are no errors? If not, try to run `bash test.sh` in that same directory.

Hope this helps,
Joeran

**Comment by jakubMitura14** [comment]
Thanks!!  I pruned all images to start fresh after build I get
```
Successfully built 7cb37b206386
Successfully tagged picai_baseline_nnunet_semi_supervised_processor:v2.1.1
Successfully tagged picai_baseline_nnunet_semi_supervised_processor:latest

```
I can not find cspca-case-level-likelihood.json anywhere in directory


after test it give the same error as earlier

**Comment by joeranbosma** [comment]
Hi @jakubMitura14,

Good to see the Docker container is now built successfully.
The subsequent error was a mistake on my part: the expected output wasn't pushed to the repository. I added this in the latest commit (https://github.com/DIAGNijmegen/picai_nnunet_semi_supervised_gc_algorithm/commit/82ba9fcc19ea4a8f875241d67e1c2482759f36cc), so after updating the repository you should be able to complete your test!

Thanks for raising this issue, and hope this means it runs smoothly now,
Joeran

**Comment by jakubMitura14** [comment]
Thanks!! now it works
